name: dotnet-check-build
run-name: Check .NET Build by ${{ github.actor }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/dotnet-check-build.yml'
      - 'dotnet/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/dotnet-build.yml
        with:
          working-directory: ./dotnet
          test: true
          package: false
